input {
  file {
    # Ruta absoluta al JSON que genera el Docker
    path => "/ruta/absoluta/a/tu/WIDS_SERVER/data/alertas_wids.json"
    
    # Le decimos que empiece a leer desde el principio del archivo
    start_position => "beginning"
    codec => "json"
  }
}

filter {
  # No necesitamos filtros porque el Python ya hace todo el trabajo sucio :)
}

output {
  # 1. Lo mandamos a la pantalla de Logstash para comprobar que funciona
  stdout { 
    codec => rubydebug 
  }

  # 2. Lo enviamos a Elasticsearch (Descomenta y pon tu IP si lo tienes levantado)
  # elasticsearch {
  #   hosts => ["http://localhost:9200"]
  #   index => "wids-alerts-%{+YYYY.MM.dd}"
  # }
}
